languaje: kotlin
jdk: oraclejdk8
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

script: ./gradlew build

#Caches
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_39d25670321c_key -iv $encrypted_39d25670321c_iv -in encripted_rsa -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
  - ssh-keyscan github.com >> ~/.ssh/known_hosts

after_success:
  - ./gradlew junitTest report jacocoRootReport coveralls
  - ssh-add -D
  - rm ~/.ssh/id_rsa